OOP school library: set up associations
naanmohammed/oop_school_library pull request #3
Opened 2023-06-25 20:03 UTC by naanmohammed

For this milestone I :

- Created a class Classroom .
- Created the has-many/belongs-to relationship between Classroom and  Student.
- Created a class Book.
- Created a class  Rental
- Created the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental.

2023-06-26 20:21 UTC, DeliceLydia requested changes
## Hi @naanmohammed, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Followed git workflow
- No linter errors
- Created the remaining classes


## Required Changes ♻️
_Check the comments under the review._



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-26 20:21 UTC, DeliceLydia commented on student.rb
> +  end
- [ ] Please add `classroom` as an `attr_reader`

2023-06-26 20:21 UTC, DeliceLydia commented on book.rb
> +  attr_reader :rentals
- [ ] I suggest that you make `rentals` as an `attr_accessor` because we need to read and modify it

2023-06-26 20:21 UTC, DeliceLydia commented on book.rb
> +  end
- [ ] To create a rental here we need `person` and `date` and the `book` itself should be sent as a parameter to create the new rental achieving the 'has-many' association
```
  def add_rental(person, date)
    Rental.new(date, self, person)
  end
```

2023-06-26 20:21 UTC, DeliceLydia commented on person.rb
> +  end
- [ ] Here you should send `date` and `book` and `The person` itself should be sent as a parameter to create the new rental achieving the 'has-many' association
```
def add_rental(book, date)
    Rental.new(book, self, date)
  end
```

2023-06-27 20:35 UTC, alexander16108 approved these changes
Hi @naanmohammed  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/S45c2ZIxpQORisbZuY/giphy-downsized-medium.gif"/>

## Highlights
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 20:38 UTC, merged